version: 0.2
phases:
  install:
    commands:
       - echo Installing source NPM dependencies
       - npm install
       - npm install -g @angular/cli

  build:
    commands:
       - echo Build started on `date`
       - ng build --prod
  post_build:
    commands:
       - echo Build completed on `date`
artifacts:
  files:
     - '**/*'
  discard-paths: yes
  base-directory: 'dist*'